### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by prabakaranP** [antonydeepak/ResumeParser#1]
I couldn't find the file 'ResumeParser' from https://github.com/antonydeepak/ResumeParser.git. Can anyone help me how to install it.

**Comment by antonydeepak** [comment]
Hello:
You must have cloned it in a different folder. Don't worry continue from the next step. i.e "cd ResumeTransducer"

**Comment by prabakaranP** [comment]
I have  downloaded Apache Tikka 1.7,But i don't know how to use that.Can you please explain how to install it and also explain how to run and test the Run Syntax.

**Comment by antonydeepak** [comment]
You don't have to install Apache Tikka. The package that I have posted is self-sufficient. You just have to following the steps under installation in readme.md file (pasted below for reference):

Installation:

Open powershell in windows (run->powershell) 
1) Git clone https://github.com/antonydeepak/ResumeParser.git 
2) cd ResumeParser 
3) cd ResumeTransducer 
4) $env:GATE_HOME="..\GATEFiles" (beware: you are giving a relative path for ease.)

I will do better package management in future.

**Comment by antonydeepak** [comment]
Lets take this step-step. What is the error you are getting?

**Comment by prabakaranP** [comment]
I got the output, But i didn't get exact json format.If i have many
resume/cv how can i use it?

**Comment by prabakaranP** [comment]
I have done all the following steps and i got the output ,But i have one doubt, Is this Okey for n number of Resumes?

**Comment by antonydeepak** [comment]
Sure, you can customize the java code to loop through all the files. Or even simpler, you can create a loop in your shell(powershell). Say, you have a folder full of resumes you can *cd* into the folder and write a powershell statement like
ls | % {java -cp '.\bin\*;..\GATEFiles\lib\*;..\GATEFILES\bin\gate.jar;.\lib\*' code4goal.antony.resumeparser.ResumeParserProgram $_.fullname "$_.name.json" }

**Comment by prabakaranP** [comment]
How can i create a loop in powershell?

**Comment by prabakaranP** [comment]
![output](https://cloud.githubusercontent.com/assets/12441042/7698981/3dab738c-fe32-11e4-8837-c5ec99efe734.png)
This is the output i am getting,I need the exact json format ,What i will do for getting json format?

**Comment by antonydeepak** [comment]
That is the .json file; probably you may have to brush-up on your fundamentals. Also, the command that I typed in my previous post is how you loop in powershell;go thru some powershell tutorial if you are not sure.
