### ISSUE TITLE
How to create a new JAR from the source in Eclipse/ IntelliJ

### ISSUE THREAD

**Issue by abhiskaushik** [antonydeepak/ResumeParser#35]
@antonydeepak  can you help me recompile the code. I've made a certain change and want to get the change reflected after running the command. How do I generate new jar or update in any common Java IDE?

Thanks,

**Comment by antonydeepak** [comment]
You can build using `ant`. 
Ref: https://github.com/antonydeepak/ResumeParser/tree/master/ResumeTransducer

**Comment by abhiskaushik** [comment]
@antonydeepak Finally I fixed it. I think two things are important to mention in your readme file:

1. The build.properties file need to be referenced to [GATE source](https://gate.ac.uk/download/)
```
# build.properties for ResumeTransducer
#
# NOTE: plugins included in the GATE default plugin directory should
# work without this file being modified. This file should not be
# checked into the subversion repository in order to allow differently
# settings for different people.
 
# gate.home - the location of your top-level GATE directory
# If your plugin is not located in the default plugins directory
# of gate (GATEHOME/plugins/) the full path of the GATE home directory
# should be specified here.
#
gate.home=D:\\gate

# The name of this plugin.
# If you want to overwrite the name as specified in the build.xml file,
# you can do it here. 
plugin.name=ResumeTransducer

# All other settings in the build.xml file can be overwritten here ...
```
2. For using `ANT` to compile and create the JAR (`/bin/Transducer.jar` file), you need to select `build.xml `file
